name: Deploy Infrastructure via Terraform

on:
  push:
    branches: [main]

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init and Apply (Dev)
      working-directory: ./envs/dev
      run: |
        terraform init -backend-config="bucket=my-terraform-states" \
                       -backend-config="prefix=cloudrun-infra/dev"
        terraform apply -var-file="dev.tfvars" -auto-approve

    - name: Terraform Init and Apply (Test)
      working-directory: ./envs/test
      run: |
        terraform init -backend-config="bucket=my-terraform-states" \
                       -backend-config="prefix=cloudrun-infra/test"
        terraform apply -var-file="test.tfvars" -auto-approve

    - name: Terraform Init and Apply (Prod)
      working-directory: ./envs/prod
      run: |
        terraform init -backend-config="bucket=my-terraform-states" \
                       -backend-config="prefix=cloudrun-infra/prod"
        terraform apply -var-file="prod.tfvars" -auto-approve
